
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProposedSlot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProposedSlot
 * 
 */
export type ProposedSlotModel = runtime.Types.Result.DefaultSelection<Prisma.$ProposedSlotPayload>

export type AggregateProposedSlot = {
  _count: ProposedSlotCountAggregateOutputType | null
  _min: ProposedSlotMinAggregateOutputType | null
  _max: ProposedSlotMaxAggregateOutputType | null
}

export type ProposedSlotMinAggregateOutputType = {
  id: string | null
  thread_id: string | null
  start_time: Date | null
  end_time: Date | null
  status: $Enums.SlotStatus | null
}

export type ProposedSlotMaxAggregateOutputType = {
  id: string | null
  thread_id: string | null
  start_time: Date | null
  end_time: Date | null
  status: $Enums.SlotStatus | null
}

export type ProposedSlotCountAggregateOutputType = {
  id: number
  thread_id: number
  start_time: number
  end_time: number
  status: number
  _all: number
}


export type ProposedSlotMinAggregateInputType = {
  id?: true
  thread_id?: true
  start_time?: true
  end_time?: true
  status?: true
}

export type ProposedSlotMaxAggregateInputType = {
  id?: true
  thread_id?: true
  start_time?: true
  end_time?: true
  status?: true
}

export type ProposedSlotCountAggregateInputType = {
  id?: true
  thread_id?: true
  start_time?: true
  end_time?: true
  status?: true
  _all?: true
}

export type ProposedSlotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProposedSlot to aggregate.
   */
  where?: Prisma.ProposedSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProposedSlots to fetch.
   */
  orderBy?: Prisma.ProposedSlotOrderByWithRelationInput | Prisma.ProposedSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProposedSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProposedSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProposedSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProposedSlots
  **/
  _count?: true | ProposedSlotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProposedSlotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProposedSlotMaxAggregateInputType
}

export type GetProposedSlotAggregateType<T extends ProposedSlotAggregateArgs> = {
      [P in keyof T & keyof AggregateProposedSlot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProposedSlot[P]>
    : Prisma.GetScalarType<T[P], AggregateProposedSlot[P]>
}




export type ProposedSlotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProposedSlotWhereInput
  orderBy?: Prisma.ProposedSlotOrderByWithAggregationInput | Prisma.ProposedSlotOrderByWithAggregationInput[]
  by: Prisma.ProposedSlotScalarFieldEnum[] | Prisma.ProposedSlotScalarFieldEnum
  having?: Prisma.ProposedSlotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProposedSlotCountAggregateInputType | true
  _min?: ProposedSlotMinAggregateInputType
  _max?: ProposedSlotMaxAggregateInputType
}

export type ProposedSlotGroupByOutputType = {
  id: string
  thread_id: string
  start_time: Date
  end_time: Date
  status: $Enums.SlotStatus
  _count: ProposedSlotCountAggregateOutputType | null
  _min: ProposedSlotMinAggregateOutputType | null
  _max: ProposedSlotMaxAggregateOutputType | null
}

type GetProposedSlotGroupByPayload<T extends ProposedSlotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProposedSlotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProposedSlotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProposedSlotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProposedSlotGroupByOutputType[P]>
      }
    >
  >



export type ProposedSlotWhereInput = {
  AND?: Prisma.ProposedSlotWhereInput | Prisma.ProposedSlotWhereInput[]
  OR?: Prisma.ProposedSlotWhereInput[]
  NOT?: Prisma.ProposedSlotWhereInput | Prisma.ProposedSlotWhereInput[]
  id?: Prisma.StringFilter<"ProposedSlot"> | string
  thread_id?: Prisma.StringFilter<"ProposedSlot"> | string
  start_time?: Prisma.DateTimeFilter<"ProposedSlot"> | Date | string
  end_time?: Prisma.DateTimeFilter<"ProposedSlot"> | Date | string
  status?: Prisma.EnumSlotStatusFilter<"ProposedSlot"> | $Enums.SlotStatus
  thread?: Prisma.XOR<Prisma.ThreadScalarRelationFilter, Prisma.ThreadWhereInput>
}

export type ProposedSlotOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  thread_id?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  status?: Prisma.SortOrder
  thread?: Prisma.ThreadOrderByWithRelationInput
}

export type ProposedSlotWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ProposedSlotWhereInput | Prisma.ProposedSlotWhereInput[]
  OR?: Prisma.ProposedSlotWhereInput[]
  NOT?: Prisma.ProposedSlotWhereInput | Prisma.ProposedSlotWhereInput[]
  thread_id?: Prisma.StringFilter<"ProposedSlot"> | string
  start_time?: Prisma.DateTimeFilter<"ProposedSlot"> | Date | string
  end_time?: Prisma.DateTimeFilter<"ProposedSlot"> | Date | string
  status?: Prisma.EnumSlotStatusFilter<"ProposedSlot"> | $Enums.SlotStatus
  thread?: Prisma.XOR<Prisma.ThreadScalarRelationFilter, Prisma.ThreadWhereInput>
}, "id">

export type ProposedSlotOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  thread_id?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  status?: Prisma.SortOrder
  _count?: Prisma.ProposedSlotCountOrderByAggregateInput
  _max?: Prisma.ProposedSlotMaxOrderByAggregateInput
  _min?: Prisma.ProposedSlotMinOrderByAggregateInput
}

export type ProposedSlotScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProposedSlotScalarWhereWithAggregatesInput | Prisma.ProposedSlotScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProposedSlotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProposedSlotScalarWhereWithAggregatesInput | Prisma.ProposedSlotScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProposedSlot"> | string
  thread_id?: Prisma.StringWithAggregatesFilter<"ProposedSlot"> | string
  start_time?: Prisma.DateTimeWithAggregatesFilter<"ProposedSlot"> | Date | string
  end_time?: Prisma.DateTimeWithAggregatesFilter<"ProposedSlot"> | Date | string
  status?: Prisma.EnumSlotStatusWithAggregatesFilter<"ProposedSlot"> | $Enums.SlotStatus
}

export type ProposedSlotCreateInput = {
  id?: string
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.SlotStatus
  thread: Prisma.ThreadCreateNestedOneWithoutProposed_slotsInput
}

export type ProposedSlotUncheckedCreateInput = {
  id?: string
  thread_id: string
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.SlotStatus
}

export type ProposedSlotUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumSlotStatusFieldUpdateOperationsInput | $Enums.SlotStatus
  thread?: Prisma.ThreadUpdateOneRequiredWithoutProposed_slotsNestedInput
}

export type ProposedSlotUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  thread_id?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumSlotStatusFieldUpdateOperationsInput | $Enums.SlotStatus
}

export type ProposedSlotCreateManyInput = {
  id?: string
  thread_id: string
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.SlotStatus
}

export type ProposedSlotUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumSlotStatusFieldUpdateOperationsInput | $Enums.SlotStatus
}

export type ProposedSlotUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  thread_id?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumSlotStatusFieldUpdateOperationsInput | $Enums.SlotStatus
}

export type ProposedSlotListRelationFilter = {
  every?: Prisma.ProposedSlotWhereInput
  some?: Prisma.ProposedSlotWhereInput
  none?: Prisma.ProposedSlotWhereInput
}

export type ProposedSlotOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProposedSlotCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  thread_id?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type ProposedSlotMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  thread_id?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type ProposedSlotMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  thread_id?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type ProposedSlotCreateNestedManyWithoutThreadInput = {
  create?: Prisma.XOR<Prisma.ProposedSlotCreateWithoutThreadInput, Prisma.ProposedSlotUncheckedCreateWithoutThreadInput> | Prisma.ProposedSlotCreateWithoutThreadInput[] | Prisma.ProposedSlotUncheckedCreateWithoutThreadInput[]
  connectOrCreate?: Prisma.ProposedSlotCreateOrConnectWithoutThreadInput | Prisma.ProposedSlotCreateOrConnectWithoutThreadInput[]
  createMany?: Prisma.ProposedSlotCreateManyThreadInputEnvelope
  connect?: Prisma.ProposedSlotWhereUniqueInput | Prisma.ProposedSlotWhereUniqueInput[]
}

export type ProposedSlotUncheckedCreateNestedManyWithoutThreadInput = {
  create?: Prisma.XOR<Prisma.ProposedSlotCreateWithoutThreadInput, Prisma.ProposedSlotUncheckedCreateWithoutThreadInput> | Prisma.ProposedSlotCreateWithoutThreadInput[] | Prisma.ProposedSlotUncheckedCreateWithoutThreadInput[]
  connectOrCreate?: Prisma.ProposedSlotCreateOrConnectWithoutThreadInput | Prisma.ProposedSlotCreateOrConnectWithoutThreadInput[]
  createMany?: Prisma.ProposedSlotCreateManyThreadInputEnvelope
  connect?: Prisma.ProposedSlotWhereUniqueInput | Prisma.ProposedSlotWhereUniqueInput[]
}

export type ProposedSlotUpdateManyWithoutThreadNestedInput = {
  create?: Prisma.XOR<Prisma.ProposedSlotCreateWithoutThreadInput, Prisma.ProposedSlotUncheckedCreateWithoutThreadInput> | Prisma.ProposedSlotCreateWithoutThreadInput[] | Prisma.ProposedSlotUncheckedCreateWithoutThreadInput[]
  connectOrCreate?: Prisma.ProposedSlotCreateOrConnectWithoutThreadInput | Prisma.ProposedSlotCreateOrConnectWithoutThreadInput[]
  upsert?: Prisma.ProposedSlotUpsertWithWhereUniqueWithoutThreadInput | Prisma.ProposedSlotUpsertWithWhereUniqueWithoutThreadInput[]
  createMany?: Prisma.ProposedSlotCreateManyThreadInputEnvelope
  set?: Prisma.ProposedSlotWhereUniqueInput | Prisma.ProposedSlotWhereUniqueInput[]
  disconnect?: Prisma.ProposedSlotWhereUniqueInput | Prisma.ProposedSlotWhereUniqueInput[]
  delete?: Prisma.ProposedSlotWhereUniqueInput | Prisma.ProposedSlotWhereUniqueInput[]
  connect?: Prisma.ProposedSlotWhereUniqueInput | Prisma.ProposedSlotWhereUniqueInput[]
  update?: Prisma.ProposedSlotUpdateWithWhereUniqueWithoutThreadInput | Prisma.ProposedSlotUpdateWithWhereUniqueWithoutThreadInput[]
  updateMany?: Prisma.ProposedSlotUpdateManyWithWhereWithoutThreadInput | Prisma.ProposedSlotUpdateManyWithWhereWithoutThreadInput[]
  deleteMany?: Prisma.ProposedSlotScalarWhereInput | Prisma.ProposedSlotScalarWhereInput[]
}

export type ProposedSlotUncheckedUpdateManyWithoutThreadNestedInput = {
  create?: Prisma.XOR<Prisma.ProposedSlotCreateWithoutThreadInput, Prisma.ProposedSlotUncheckedCreateWithoutThreadInput> | Prisma.ProposedSlotCreateWithoutThreadInput[] | Prisma.ProposedSlotUncheckedCreateWithoutThreadInput[]
  connectOrCreate?: Prisma.ProposedSlotCreateOrConnectWithoutThreadInput | Prisma.ProposedSlotCreateOrConnectWithoutThreadInput[]
  upsert?: Prisma.ProposedSlotUpsertWithWhereUniqueWithoutThreadInput | Prisma.ProposedSlotUpsertWithWhereUniqueWithoutThreadInput[]
  createMany?: Prisma.ProposedSlotCreateManyThreadInputEnvelope
  set?: Prisma.ProposedSlotWhereUniqueInput | Prisma.ProposedSlotWhereUniqueInput[]
  disconnect?: Prisma.ProposedSlotWhereUniqueInput | Prisma.ProposedSlotWhereUniqueInput[]
  delete?: Prisma.ProposedSlotWhereUniqueInput | Prisma.ProposedSlotWhereUniqueInput[]
  connect?: Prisma.ProposedSlotWhereUniqueInput | Prisma.ProposedSlotWhereUniqueInput[]
  update?: Prisma.ProposedSlotUpdateWithWhereUniqueWithoutThreadInput | Prisma.ProposedSlotUpdateWithWhereUniqueWithoutThreadInput[]
  updateMany?: Prisma.ProposedSlotUpdateManyWithWhereWithoutThreadInput | Prisma.ProposedSlotUpdateManyWithWhereWithoutThreadInput[]
  deleteMany?: Prisma.ProposedSlotScalarWhereInput | Prisma.ProposedSlotScalarWhereInput[]
}

export type EnumSlotStatusFieldUpdateOperationsInput = {
  set?: $Enums.SlotStatus
}

export type ProposedSlotCreateWithoutThreadInput = {
  id?: string
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.SlotStatus
}

export type ProposedSlotUncheckedCreateWithoutThreadInput = {
  id?: string
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.SlotStatus
}

export type ProposedSlotCreateOrConnectWithoutThreadInput = {
  where: Prisma.ProposedSlotWhereUniqueInput
  create: Prisma.XOR<Prisma.ProposedSlotCreateWithoutThreadInput, Prisma.ProposedSlotUncheckedCreateWithoutThreadInput>
}

export type ProposedSlotCreateManyThreadInputEnvelope = {
  data: Prisma.ProposedSlotCreateManyThreadInput | Prisma.ProposedSlotCreateManyThreadInput[]
  skipDuplicates?: boolean
}

export type ProposedSlotUpsertWithWhereUniqueWithoutThreadInput = {
  where: Prisma.ProposedSlotWhereUniqueInput
  update: Prisma.XOR<Prisma.ProposedSlotUpdateWithoutThreadInput, Prisma.ProposedSlotUncheckedUpdateWithoutThreadInput>
  create: Prisma.XOR<Prisma.ProposedSlotCreateWithoutThreadInput, Prisma.ProposedSlotUncheckedCreateWithoutThreadInput>
}

export type ProposedSlotUpdateWithWhereUniqueWithoutThreadInput = {
  where: Prisma.ProposedSlotWhereUniqueInput
  data: Prisma.XOR<Prisma.ProposedSlotUpdateWithoutThreadInput, Prisma.ProposedSlotUncheckedUpdateWithoutThreadInput>
}

export type ProposedSlotUpdateManyWithWhereWithoutThreadInput = {
  where: Prisma.ProposedSlotScalarWhereInput
  data: Prisma.XOR<Prisma.ProposedSlotUpdateManyMutationInput, Prisma.ProposedSlotUncheckedUpdateManyWithoutThreadInput>
}

export type ProposedSlotScalarWhereInput = {
  AND?: Prisma.ProposedSlotScalarWhereInput | Prisma.ProposedSlotScalarWhereInput[]
  OR?: Prisma.ProposedSlotScalarWhereInput[]
  NOT?: Prisma.ProposedSlotScalarWhereInput | Prisma.ProposedSlotScalarWhereInput[]
  id?: Prisma.StringFilter<"ProposedSlot"> | string
  thread_id?: Prisma.StringFilter<"ProposedSlot"> | string
  start_time?: Prisma.DateTimeFilter<"ProposedSlot"> | Date | string
  end_time?: Prisma.DateTimeFilter<"ProposedSlot"> | Date | string
  status?: Prisma.EnumSlotStatusFilter<"ProposedSlot"> | $Enums.SlotStatus
}

export type ProposedSlotCreateManyThreadInput = {
  id?: string
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.SlotStatus
}

export type ProposedSlotUpdateWithoutThreadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumSlotStatusFieldUpdateOperationsInput | $Enums.SlotStatus
}

export type ProposedSlotUncheckedUpdateWithoutThreadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumSlotStatusFieldUpdateOperationsInput | $Enums.SlotStatus
}

export type ProposedSlotUncheckedUpdateManyWithoutThreadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumSlotStatusFieldUpdateOperationsInput | $Enums.SlotStatus
}



export type ProposedSlotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  thread_id?: boolean
  start_time?: boolean
  end_time?: boolean
  status?: boolean
  thread?: boolean | Prisma.ThreadDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proposedSlot"]>

export type ProposedSlotSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  thread_id?: boolean
  start_time?: boolean
  end_time?: boolean
  status?: boolean
  thread?: boolean | Prisma.ThreadDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proposedSlot"]>

export type ProposedSlotSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  thread_id?: boolean
  start_time?: boolean
  end_time?: boolean
  status?: boolean
  thread?: boolean | Prisma.ThreadDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proposedSlot"]>

export type ProposedSlotSelectScalar = {
  id?: boolean
  thread_id?: boolean
  start_time?: boolean
  end_time?: boolean
  status?: boolean
}

export type ProposedSlotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "thread_id" | "start_time" | "end_time" | "status", ExtArgs["result"]["proposedSlot"]>
export type ProposedSlotInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  thread?: boolean | Prisma.ThreadDefaultArgs<ExtArgs>
}
export type ProposedSlotIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  thread?: boolean | Prisma.ThreadDefaultArgs<ExtArgs>
}
export type ProposedSlotIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  thread?: boolean | Prisma.ThreadDefaultArgs<ExtArgs>
}

export type $ProposedSlotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProposedSlot"
  objects: {
    thread: Prisma.$ThreadPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    thread_id: string
    start_time: Date
    end_time: Date
    status: $Enums.SlotStatus
  }, ExtArgs["result"]["proposedSlot"]>
  composites: {}
}

export type ProposedSlotGetPayload<S extends boolean | null | undefined | ProposedSlotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProposedSlotPayload, S>

export type ProposedSlotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProposedSlotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProposedSlotCountAggregateInputType | true
  }

export interface ProposedSlotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProposedSlot'], meta: { name: 'ProposedSlot' } }
  /**
   * Find zero or one ProposedSlot that matches the filter.
   * @param {ProposedSlotFindUniqueArgs} args - Arguments to find a ProposedSlot
   * @example
   * // Get one ProposedSlot
   * const proposedSlot = await prisma.proposedSlot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProposedSlotFindUniqueArgs>(args: Prisma.SelectSubset<T, ProposedSlotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProposedSlotClient<runtime.Types.Result.GetResult<Prisma.$ProposedSlotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProposedSlot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProposedSlotFindUniqueOrThrowArgs} args - Arguments to find a ProposedSlot
   * @example
   * // Get one ProposedSlot
   * const proposedSlot = await prisma.proposedSlot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProposedSlotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProposedSlotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProposedSlotClient<runtime.Types.Result.GetResult<Prisma.$ProposedSlotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProposedSlot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposedSlotFindFirstArgs} args - Arguments to find a ProposedSlot
   * @example
   * // Get one ProposedSlot
   * const proposedSlot = await prisma.proposedSlot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProposedSlotFindFirstArgs>(args?: Prisma.SelectSubset<T, ProposedSlotFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProposedSlotClient<runtime.Types.Result.GetResult<Prisma.$ProposedSlotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProposedSlot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposedSlotFindFirstOrThrowArgs} args - Arguments to find a ProposedSlot
   * @example
   * // Get one ProposedSlot
   * const proposedSlot = await prisma.proposedSlot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProposedSlotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProposedSlotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProposedSlotClient<runtime.Types.Result.GetResult<Prisma.$ProposedSlotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProposedSlots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposedSlotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProposedSlots
   * const proposedSlots = await prisma.proposedSlot.findMany()
   * 
   * // Get first 10 ProposedSlots
   * const proposedSlots = await prisma.proposedSlot.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const proposedSlotWithIdOnly = await prisma.proposedSlot.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProposedSlotFindManyArgs>(args?: Prisma.SelectSubset<T, ProposedSlotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProposedSlotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProposedSlot.
   * @param {ProposedSlotCreateArgs} args - Arguments to create a ProposedSlot.
   * @example
   * // Create one ProposedSlot
   * const ProposedSlot = await prisma.proposedSlot.create({
   *   data: {
   *     // ... data to create a ProposedSlot
   *   }
   * })
   * 
   */
  create<T extends ProposedSlotCreateArgs>(args: Prisma.SelectSubset<T, ProposedSlotCreateArgs<ExtArgs>>): Prisma.Prisma__ProposedSlotClient<runtime.Types.Result.GetResult<Prisma.$ProposedSlotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProposedSlots.
   * @param {ProposedSlotCreateManyArgs} args - Arguments to create many ProposedSlots.
   * @example
   * // Create many ProposedSlots
   * const proposedSlot = await prisma.proposedSlot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProposedSlotCreateManyArgs>(args?: Prisma.SelectSubset<T, ProposedSlotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProposedSlots and returns the data saved in the database.
   * @param {ProposedSlotCreateManyAndReturnArgs} args - Arguments to create many ProposedSlots.
   * @example
   * // Create many ProposedSlots
   * const proposedSlot = await prisma.proposedSlot.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProposedSlots and only return the `id`
   * const proposedSlotWithIdOnly = await prisma.proposedSlot.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProposedSlotCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProposedSlotCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProposedSlotPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProposedSlot.
   * @param {ProposedSlotDeleteArgs} args - Arguments to delete one ProposedSlot.
   * @example
   * // Delete one ProposedSlot
   * const ProposedSlot = await prisma.proposedSlot.delete({
   *   where: {
   *     // ... filter to delete one ProposedSlot
   *   }
   * })
   * 
   */
  delete<T extends ProposedSlotDeleteArgs>(args: Prisma.SelectSubset<T, ProposedSlotDeleteArgs<ExtArgs>>): Prisma.Prisma__ProposedSlotClient<runtime.Types.Result.GetResult<Prisma.$ProposedSlotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProposedSlot.
   * @param {ProposedSlotUpdateArgs} args - Arguments to update one ProposedSlot.
   * @example
   * // Update one ProposedSlot
   * const proposedSlot = await prisma.proposedSlot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProposedSlotUpdateArgs>(args: Prisma.SelectSubset<T, ProposedSlotUpdateArgs<ExtArgs>>): Prisma.Prisma__ProposedSlotClient<runtime.Types.Result.GetResult<Prisma.$ProposedSlotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProposedSlots.
   * @param {ProposedSlotDeleteManyArgs} args - Arguments to filter ProposedSlots to delete.
   * @example
   * // Delete a few ProposedSlots
   * const { count } = await prisma.proposedSlot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProposedSlotDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProposedSlotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProposedSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposedSlotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProposedSlots
   * const proposedSlot = await prisma.proposedSlot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProposedSlotUpdateManyArgs>(args: Prisma.SelectSubset<T, ProposedSlotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProposedSlots and returns the data updated in the database.
   * @param {ProposedSlotUpdateManyAndReturnArgs} args - Arguments to update many ProposedSlots.
   * @example
   * // Update many ProposedSlots
   * const proposedSlot = await prisma.proposedSlot.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProposedSlots and only return the `id`
   * const proposedSlotWithIdOnly = await prisma.proposedSlot.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProposedSlotUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProposedSlotUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProposedSlotPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProposedSlot.
   * @param {ProposedSlotUpsertArgs} args - Arguments to update or create a ProposedSlot.
   * @example
   * // Update or create a ProposedSlot
   * const proposedSlot = await prisma.proposedSlot.upsert({
   *   create: {
   *     // ... data to create a ProposedSlot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProposedSlot we want to update
   *   }
   * })
   */
  upsert<T extends ProposedSlotUpsertArgs>(args: Prisma.SelectSubset<T, ProposedSlotUpsertArgs<ExtArgs>>): Prisma.Prisma__ProposedSlotClient<runtime.Types.Result.GetResult<Prisma.$ProposedSlotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProposedSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposedSlotCountArgs} args - Arguments to filter ProposedSlots to count.
   * @example
   * // Count the number of ProposedSlots
   * const count = await prisma.proposedSlot.count({
   *   where: {
   *     // ... the filter for the ProposedSlots we want to count
   *   }
   * })
  **/
  count<T extends ProposedSlotCountArgs>(
    args?: Prisma.Subset<T, ProposedSlotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProposedSlotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProposedSlot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposedSlotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProposedSlotAggregateArgs>(args: Prisma.Subset<T, ProposedSlotAggregateArgs>): Prisma.PrismaPromise<GetProposedSlotAggregateType<T>>

  /**
   * Group by ProposedSlot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposedSlotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProposedSlotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProposedSlotGroupByArgs['orderBy'] }
      : { orderBy?: ProposedSlotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProposedSlotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProposedSlotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProposedSlot model
 */
readonly fields: ProposedSlotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProposedSlot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProposedSlotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  thread<T extends Prisma.ThreadDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ThreadDefaultArgs<ExtArgs>>): Prisma.Prisma__ThreadClient<runtime.Types.Result.GetResult<Prisma.$ThreadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProposedSlot model
 */
export interface ProposedSlotFieldRefs {
  readonly id: Prisma.FieldRef<"ProposedSlot", 'String'>
  readonly thread_id: Prisma.FieldRef<"ProposedSlot", 'String'>
  readonly start_time: Prisma.FieldRef<"ProposedSlot", 'DateTime'>
  readonly end_time: Prisma.FieldRef<"ProposedSlot", 'DateTime'>
  readonly status: Prisma.FieldRef<"ProposedSlot", 'SlotStatus'>
}
    

// Custom InputTypes
/**
 * ProposedSlot findUnique
 */
export type ProposedSlotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProposedSlot
   */
  select?: Prisma.ProposedSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProposedSlot
   */
  omit?: Prisma.ProposedSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposedSlotInclude<ExtArgs> | null
  /**
   * Filter, which ProposedSlot to fetch.
   */
  where: Prisma.ProposedSlotWhereUniqueInput
}

/**
 * ProposedSlot findUniqueOrThrow
 */
export type ProposedSlotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProposedSlot
   */
  select?: Prisma.ProposedSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProposedSlot
   */
  omit?: Prisma.ProposedSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposedSlotInclude<ExtArgs> | null
  /**
   * Filter, which ProposedSlot to fetch.
   */
  where: Prisma.ProposedSlotWhereUniqueInput
}

/**
 * ProposedSlot findFirst
 */
export type ProposedSlotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProposedSlot
   */
  select?: Prisma.ProposedSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProposedSlot
   */
  omit?: Prisma.ProposedSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposedSlotInclude<ExtArgs> | null
  /**
   * Filter, which ProposedSlot to fetch.
   */
  where?: Prisma.ProposedSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProposedSlots to fetch.
   */
  orderBy?: Prisma.ProposedSlotOrderByWithRelationInput | Prisma.ProposedSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProposedSlots.
   */
  cursor?: Prisma.ProposedSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProposedSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProposedSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProposedSlots.
   */
  distinct?: Prisma.ProposedSlotScalarFieldEnum | Prisma.ProposedSlotScalarFieldEnum[]
}

/**
 * ProposedSlot findFirstOrThrow
 */
export type ProposedSlotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProposedSlot
   */
  select?: Prisma.ProposedSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProposedSlot
   */
  omit?: Prisma.ProposedSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposedSlotInclude<ExtArgs> | null
  /**
   * Filter, which ProposedSlot to fetch.
   */
  where?: Prisma.ProposedSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProposedSlots to fetch.
   */
  orderBy?: Prisma.ProposedSlotOrderByWithRelationInput | Prisma.ProposedSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProposedSlots.
   */
  cursor?: Prisma.ProposedSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProposedSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProposedSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProposedSlots.
   */
  distinct?: Prisma.ProposedSlotScalarFieldEnum | Prisma.ProposedSlotScalarFieldEnum[]
}

/**
 * ProposedSlot findMany
 */
export type ProposedSlotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProposedSlot
   */
  select?: Prisma.ProposedSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProposedSlot
   */
  omit?: Prisma.ProposedSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposedSlotInclude<ExtArgs> | null
  /**
   * Filter, which ProposedSlots to fetch.
   */
  where?: Prisma.ProposedSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProposedSlots to fetch.
   */
  orderBy?: Prisma.ProposedSlotOrderByWithRelationInput | Prisma.ProposedSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProposedSlots.
   */
  cursor?: Prisma.ProposedSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProposedSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProposedSlots.
   */
  skip?: number
  distinct?: Prisma.ProposedSlotScalarFieldEnum | Prisma.ProposedSlotScalarFieldEnum[]
}

/**
 * ProposedSlot create
 */
export type ProposedSlotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProposedSlot
   */
  select?: Prisma.ProposedSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProposedSlot
   */
  omit?: Prisma.ProposedSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposedSlotInclude<ExtArgs> | null
  /**
   * The data needed to create a ProposedSlot.
   */
  data: Prisma.XOR<Prisma.ProposedSlotCreateInput, Prisma.ProposedSlotUncheckedCreateInput>
}

/**
 * ProposedSlot createMany
 */
export type ProposedSlotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProposedSlots.
   */
  data: Prisma.ProposedSlotCreateManyInput | Prisma.ProposedSlotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProposedSlot createManyAndReturn
 */
export type ProposedSlotCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProposedSlot
   */
  select?: Prisma.ProposedSlotSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProposedSlot
   */
  omit?: Prisma.ProposedSlotOmit<ExtArgs> | null
  /**
   * The data used to create many ProposedSlots.
   */
  data: Prisma.ProposedSlotCreateManyInput | Prisma.ProposedSlotCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposedSlotIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProposedSlot update
 */
export type ProposedSlotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProposedSlot
   */
  select?: Prisma.ProposedSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProposedSlot
   */
  omit?: Prisma.ProposedSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposedSlotInclude<ExtArgs> | null
  /**
   * The data needed to update a ProposedSlot.
   */
  data: Prisma.XOR<Prisma.ProposedSlotUpdateInput, Prisma.ProposedSlotUncheckedUpdateInput>
  /**
   * Choose, which ProposedSlot to update.
   */
  where: Prisma.ProposedSlotWhereUniqueInput
}

/**
 * ProposedSlot updateMany
 */
export type ProposedSlotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProposedSlots.
   */
  data: Prisma.XOR<Prisma.ProposedSlotUpdateManyMutationInput, Prisma.ProposedSlotUncheckedUpdateManyInput>
  /**
   * Filter which ProposedSlots to update
   */
  where?: Prisma.ProposedSlotWhereInput
  /**
   * Limit how many ProposedSlots to update.
   */
  limit?: number
}

/**
 * ProposedSlot updateManyAndReturn
 */
export type ProposedSlotUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProposedSlot
   */
  select?: Prisma.ProposedSlotSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProposedSlot
   */
  omit?: Prisma.ProposedSlotOmit<ExtArgs> | null
  /**
   * The data used to update ProposedSlots.
   */
  data: Prisma.XOR<Prisma.ProposedSlotUpdateManyMutationInput, Prisma.ProposedSlotUncheckedUpdateManyInput>
  /**
   * Filter which ProposedSlots to update
   */
  where?: Prisma.ProposedSlotWhereInput
  /**
   * Limit how many ProposedSlots to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposedSlotIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProposedSlot upsert
 */
export type ProposedSlotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProposedSlot
   */
  select?: Prisma.ProposedSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProposedSlot
   */
  omit?: Prisma.ProposedSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposedSlotInclude<ExtArgs> | null
  /**
   * The filter to search for the ProposedSlot to update in case it exists.
   */
  where: Prisma.ProposedSlotWhereUniqueInput
  /**
   * In case the ProposedSlot found by the `where` argument doesn't exist, create a new ProposedSlot with this data.
   */
  create: Prisma.XOR<Prisma.ProposedSlotCreateInput, Prisma.ProposedSlotUncheckedCreateInput>
  /**
   * In case the ProposedSlot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProposedSlotUpdateInput, Prisma.ProposedSlotUncheckedUpdateInput>
}

/**
 * ProposedSlot delete
 */
export type ProposedSlotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProposedSlot
   */
  select?: Prisma.ProposedSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProposedSlot
   */
  omit?: Prisma.ProposedSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposedSlotInclude<ExtArgs> | null
  /**
   * Filter which ProposedSlot to delete.
   */
  where: Prisma.ProposedSlotWhereUniqueInput
}

/**
 * ProposedSlot deleteMany
 */
export type ProposedSlotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProposedSlots to delete
   */
  where?: Prisma.ProposedSlotWhereInput
  /**
   * Limit how many ProposedSlots to delete.
   */
  limit?: number
}

/**
 * ProposedSlot without action
 */
export type ProposedSlotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProposedSlot
   */
  select?: Prisma.ProposedSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProposedSlot
   */
  omit?: Prisma.ProposedSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposedSlotInclude<ExtArgs> | null
}
